name: release-pr

on:
  pull_request:
    branches: ["main"]

jobs:
  test-and-build:
    uses: ./.github/workflows/test.yml
    if: (startsWith(github.head_ref, 'release/') && !github.event.pull_request.head.repo.fork)
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  prepare-release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Create Tag
        run: |
          TAG="${GITHUB_HEAD_REF#release/}"
          if [[ $(gh api /repos/autopp/go-serverify/releases | jq "any(.name == \"${TAG}\" and .draft == true)") = true ]]; then
            echo Delete existing release
            gh release delete "${TAG}"
          fi
          gh release create "${TAG}" --title "${TAG}" --draft
  teardown:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    needs: prepare-release
    steps:
    - name: Notify to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,took,workflow,job,ref,message
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
