name: test

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      CODECOV_TOKEN:
        required: true

jobs:
  test-and-build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Use Cache
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
      id: cache
    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        go mod download
    - name: Run Test
      id: unittest
      run: |
        go install github.com/onsi/ginkgo/v2/ginkgo@$(go list -f '{{.Version}}' -m github.com/onsi/ginkgo/v2 || echo 'LOOKUP-VERSION-FAILED')
        make test
    - uses: codecov/codecov-action@v4
      with:
        file: ./coverprofile.out
        token: ${{ secrets.CODECOV_TOKEN }}
      if: ${{ steps.unittest.conclusion == 'success' || steps.unittest.conclusion == 'failure' }}
    - name: Build
      run: go build
    - name: Notify to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,took,workflow,job,ref,message
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: failure() || cancelled()
